In [1]:
import pandas as pd
hypo=['%']*6

In [2]:
data = pd.read_csv("trainingdata.csv")
print("\n The given training examples are  \n")
print(data)

 The given training examples are

     sky airTemp humidity    wind water forecast enjoySport
0  Sunny    Warm   Normal  Strong  Warm     Same        Yes
1  Sunny    Warm     High  Strong  Warm     Same        Yes
2  Rainy    Cold     High  Strong  Warm   Change         No
3  Sunny    Warm     High  Strong  Cool   Change        Yes

In [3]:
#filtiring the positive exaples

positive_examples=data[data.iloc[:,-1]=='Yes'] # : represents all rows
positive_examples

     sky airTemp humidity    wind water forecast enjoySport
0  Sunny    Warm   Normal  Strong  Warm     Same        Yes
1  Sunny    Warm     High  Strong  Warm     Same        Yes
3  Sunny    Warm     High  Strong  Cool   Change        Yes

In [29]:
#initializing the 1st positive as an hypotesis

hypo=positive_examples.iloc[0,:-1].tolist() #tolist() is used group the attributes in a list
print('Initial hypothesis \n',hypo)

Initial hypothesis
 ['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same']

In [30]:
#Implementing the FIND-S algorithm

for i in range (1,len(positive_examples)):
    print("\nIteration ",i)
    print("Current hpothesis :",hypo)
    for j in range(len(hypo)):
        if hypo[j]!=positive_examples.iloc[i,j]:
            hypo[j]='?'
    print("Updated hypothesis :",hypo)

Iteration  1
Current hpothesis : ['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same']
Updated hypothesis : ['Sunny', 'Warm', '?', 'Strong', 'Warm', 'Same']

Iteration  2
Current hpothesis : ['Sunny', 'Warm', '?', 'Strong', 'Warm', 'Same']
Updated hypothesis : ['Sunny', 'Warm', '?', 'Strong', '?', '?']

In [31]:
hypo

['Sunny', 'Warm', '?', 'Strong', '?', '?']

In [33]:
#SAMPLES

In [34]:
df = pd.read_csv("trainingdata2.csv")
print("\n The given training examples are  \n")
print(df)

 The given training examples are

    COLOR TOUGHNESS FUNGUS APPEARANCE POISONOUS
0   GREEN      HARD     NO   WRINKLED       YES
1   GREEN      HARD    YES     SMOOTH        NO
2   BROWN      SOFT     NO   WRINKLED        NO
3  ORANGE      HARD     NO   WRINKLED       YES
4   GREEN      SOFT    YES     SMOOTH       YES
5   GREEN      HARD    YES   WRINKLED       YES
6  ORANGE      HARD     NO   WRINKLED       YES

In [44]:
positive_outcomes=df[df.iloc[:,-1]=='YES']
positive_outcomes

    COLOR TOUGHNESS FUNGUS APPEARANCE POISONOUS
0   GREEN      HARD     NO   WRINKLED       YES
3  ORANGE      HARD     NO   WRINKLED       YES
4   GREEN      SOFT    YES     SMOOTH       YES
5   GREEN      HARD    YES   WRINKLED       YES
6  ORANGE      HARD     NO   WRINKLED       YES

In [47]:
hypothesis=positive_outcomes.iloc[0,:-1].tolist()
hypothesis

['GREEN', 'HARD', 'NO', 'WRINKLED']

In [48]:
for i in range(1,len(positive_outcomes)):
    print("\nIteration ",i)
    print(hypothesis)
    for j in range(len(hypothesis)):
        if hypothesis[j]!=positive_outcomes.iloc[i,j]:
            hypothesis[j]='?'
    print(hypothesis)

Iteration  1
['GREEN', 'HARD', 'NO', 'WRINKLED']
['?', 'HARD', 'NO', 'WRINKLED']

Iteration  2
['?', 'HARD', 'NO', 'WRINKLED']
['?', '?', '?', '?']

Iteration  3
['?', '?', '?', '?']
['?', '?', '?', '?']

Iteration  4
['?', '?', '?', '?']
['?', '?', '?', '?']

In [4]:
import pandas as pd

In [7]:
data=pd.read_csv('trainingdata.csv')
print(data)

     sky airTemp humidity    wind water forecast enjoySport
0  Sunny    Warm   Normal  Strong  Warm     Same        Yes
1  Sunny    Warm     High  Strong  Warm     Same        Yes
2  Rainy    Cold     High  Strong  Warm   Change         No
3  Sunny    Warm     High  Strong  Cool   Change        Yes

In [9]:
positive_examples=data[data.iloc[:,-1]=="Yes"]

In [10]:
positive_examples

     sky airTemp humidity    wind water forecast enjoySport
0  Sunny    Warm   Normal  Strong  Warm     Same        Yes
1  Sunny    Warm     High  Strong  Warm     Same        Yes
3  Sunny    Warm     High  Strong  Cool   Change        Yes

In [11]:
hypo=positive_examples.iloc[0,:-1].tolist()

In [12]:
hypo

['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same']

In [16]:
for i in range(1,len(positive_examples)):
    print("\nInitial :",hypo)
    for j in range(len(hypo)):
        if hypo[j]!=positive_examples.iloc[i,j]:
            hypo[j]='?'
    print("After :",hypo)

Initial : ['Sunny', 'Warm', '?', 'Strong', '?', '?']
After : ['Sunny', 'Warm', '?', 'Strong', '?', '?']

Initial : ['Sunny', 'Warm', '?', 'Strong', '?', '?']
After : ['Sunny', 'Warm', '?', 'Strong', '?', '?']